### ISSUE TITLE
joint_position_controller_dual_motor.py not working

### ISSUE THREAD

**Issue by SietseAchterop** [arebgun/dynamixel_motor#32]
Hello,
I have an ax18a arm from crustcrawler.
Using the tutorial code a single joint position controller works perfectly, but the dual version does not behave or  gives an error when asked to go to a position via
    rostopic pub -1 /dual_motor_controller/command std_msgs/Float64 -- 1.5

It then starts to move with a certain speed and doesn't stop untill it blocks and the servo overloads.
If I give a negative value, nothing moves, but the manager gives:

[ERROR] [WallTime: 1427120241.881864] bad callback: <bound method JointPositionControllerDual.process_command of <dynamixel_controllers.joint_position_controller_dual_motor.JointPositionControllerDual instance at 0x7f1fa4941e60>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/DTPAlab/Software/catkin_ws/src/dynamixel_motor-master/dynamixel_controllers/src/dynamixel_controllers/joint_position_controller_dual_motor.py", line 205, in process_command
    self.dxl_io.set_multi_position([mcv_master, mcv_slave])
  File "/DTPAlab/Software/catkin_ws/src/dynamixel_motor-master/dynamixel_driver/src/dynamixel_driver/dynamixel_io.py", line 726, in set_multi_position
    self.sync_write(DXL_GOAL_POSITION_L, writeableVals)
  File "/DTPAlab/Software/catkin_ws/src/dynamixel_motor-master/dynamixel_driver/src/dynamixel_driver/dynamixel_io.py", line 213, in sync_write
    packetStr = array('B', packet).tostring() # packetStr = ''.join([chr(byte) for byte in packet])
OverflowError: unsigned byte integer is less than minimum
===================================================

This is with the latest "master" version. I also tried the version "in" indigo.
The only thing I changed in the tutorial are the ID's of the servo's.

What could I do next?
    Thanks in advance,
         Sietse

**Comment by SietseAchterop** [comment]
Solved the problem. It had nothing to do with the software, the arm was incorrectly assembled.
Sorry to bother you
