### ISSUE TITLE
Errors in dynamixel_controllers/tutorial/meta_controller in indigo

### ISSUE THREAD

**Issue by SietseAchterop** [arebgun/dynamixel_motor#33]
Hello,
I'm using the ax-18a arm from crustcrawler with ros/indigo, and try to get the tutorial example working.
Using the dynamixel packages from indigo the tilt and dual controllers work fine.
But the starting the meta_controller (action server) gives errors in the controller, see the log below.
Installing the github-master version solved this problem. Now the meta controller can start and loads all 5 controllers.

But starting "trajectory_client.py" from the tutorial, after a few seconds gives also errors in the controller.
To me it looks like a python error, but I am a bit stuck here. Where to look for the error?

Please find log fragments of the two errors below. It is of course the second problem that i'm hoping to solve.
  Hopefully someone can enlighten me,
      Thanks in advance,
          Sietse

====  fragment of controller output using the dynamixel packages from indigo:

<pre>

[ERROR] [WallTime: 1427361968.393688] bad callback: <bound method JointPositionControllerDual.process_motor_states of <dynamixel_controllers.joint_position_controller_dual_motor.JointPositionControllerDual instance at 0x7faaf843f2d8>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamixel_controllers/joint_position_controller_dual_motor.py", line 166, in process_motor_states
    self.joint_state.motor_temps = [state.temperature, states[self.slave_id].temperature]
KeyError: 3

</pre>

====== fragment using the version from github:

<pre>
[ERROR] [WallTime: 1427362674.605134] Exception in your execute callback: Invalid number of arguments, args should be ['error_code', 'error_string'] args are(-2,)
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 299, in executeLoop
    self.execute_callback(goal)
  File "/DTPAlab/Software/catkin_ws/src/dynamixel_motor-master/dynamixel_controllers/src/dynamixel_controllers/joint_trajectory_action_controller.py", line 142, in process_follow_trajectory
    self.process_trajectory(goal.trajectory)
  File "/DTPAlab/Software/catkin_ws/src/dynamixel_motor-master/dynamixel_controllers/src/dynamixel_controllers/joint_trajectory_action_controller.py", line 149, in process_trajectory
    res = FollowJointTrajectoryResult(FollowJointTrajectoryResult.INVALID_JOINTS)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/control_msgs/msg/_FollowJointTrajectoryResult.py", line 59, in __init__
    super(FollowJointTrajectoryResult, self).__init__(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genpy/message.py", line 291, in __init__
    raise TypeError("Invalid number of arguments, args should be %s"%str(self.__slots__)+" args are"+str(args))
TypeError: Invalid number of arguments, args should be ['error_code', 'error_string'] args are(-2,)

</pre>

**Comment by vncprado** [comment]
Hi, I'm having a similar problem on ROS Indigo even when the trajectory is successful.

`[ERROR] [WallTime: 1476749262.315773] Exception in your execute callback: Invalid number of arguments, args should be ['error_code', 'error_string'] args are(0,)
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 291, in executeLoop
    self.execute_callback(goal)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamixel_controllers/joint_trajectory_action_controller.py", line 142, in process_follow_trajectory
    self.process_trajectory(goal.trajectory)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamixel_controllers/joint_trajectory_action_controller.py", line 324, in process_trajectory
    res = FollowJointTrajectoryResult(FollowJointTrajectoryResult.SUCCESSFUL)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/control_msgs/msg/_FollowJointTrajectoryResult.py", line 59, in __init__
    super(FollowJointTrajectoryResult, self).__init__(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genpy/message.py", line 291, in __init__
    raise TypeError("Invalid number of arguments, args should be %s"%str(self.__slots__)+" args are"+str(args))
TypeError: Invalid number of arguments, args should be ['error_code', 'error_string'] args are(0,)`
