### ISSUE TITLE
DroppedPacketError: Invalid response received from motor 7. Wrong packet prefix []

### ISSUE THREAD

**Issue by 130s** [arebgun/dynamixel_motor#35]
I know I can now make a new release of this package but I'm hesitant because with the [latest source](https://github.com/arebgun/dynamixel_motor/commit/4f79026beb414a33f2b76e2a463952a5c9581158) I've seen the following error (originally reported in a downstream https://github.com/tork-a/spur/issues/4). 

Despite the error the motors still seem to function so far to me. I'm just afraid if making a new release with error msgs like this is a good idea. If someone can give feedback (eg. how significant is this) that would be great.

```
[WARN] [WallTime: 1425527484.001281] [joint_state_publisher] not all dependencies started, still waiting for ['br_wheel_joint_velocity_controller', 'fr_wheel_joint_velocity_controller']...
[INFO] [WallTime: 1425527484.001691] Controller bl_wheel_joint_velocity_controller successfully started.
[WARN] [WallTime: 1425527484.022211] [joint_state_publisher] not all dependencies started, still waiting for ['fr_wheel_joint_velocity_controller']...
[INFO] [WallTime: 1425527484.022693] Controller br_wheel_joint_velocity_controller successfully started.
[INFO] [WallTime: 1425527484.045974] Controller fr_wheel_joint_velocity_controller successfully started.
[spur/dynamixel_controller_spawner_MX106-3] process has finished cleanly
log file: /home/rostam/.ros/log/e30190b0-c2ea-11e4-8535-f816542d218e/spur-dynamixel_controller_spawner_MX106-3*.log
[INFO] [WallTime: 1425527485.059876] Start base controller
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rostam/cws_spur/src/dynamixel_motor/dynamixel_controllers/src/dynamixel_controllers/joint_state_publisher.py", line 100, in update_state
  File "/home/rostam/cws_spur/src/dynamixel_motor/dynamixel_driver/src/dynamixel_driver/dynamixel_io.py", line 891, in get_current
    model = self.get_model_number(servo_id)
  File "/home/rostam/cws_spur/src/dynamixel_motor/dynamixel_driver/src/dynamixel_driver/dynamixel_io.py", line 809, in get_model_number
    response = self.read(servo_id, DXL_MODEL_NUMBER_L, 2)
  File "/home/rostam/cws_spur/src/dynamixel_motor/dynamixel_driver/src/dynamixel_driver/dynamixel_io.py", line 141, in read
    data = self.__read_response(servo_id)
  File "/home/rostam/cws_spur/src/dynamixel_motor/dynamixel_driver/src/dynamixel_driver/dynamixel_io.py", line 104, in __read_response
    raise DroppedPacketError('Invalid response received from motor %d. %s' % (servo_id, e))
DroppedPacketError: Invalid response received from motor 7. Wrong packet prefix []
```

**Comment by 130s** [comment]
I checked [the latest commit](https://github.com/arebgun/dynamixel_motor/commit/4f79026beb414a33f2b76e2a463952a5c9581158) with AX12 and so far I haven't seen this error. So this issue perhaps only has a minor impact for making new release.

**Comment by Achllle** [comment]
I'm still getting this error sporadically on the MX-64s. @130s I don't see how that commit is related, did you do anything else to fix this?

**Comment by Achllle** [comment]
The problem is definitely with the hardware connections. We were able to replicate DroppedPacketErrors by wiggling the 3-pin wires between individual motors. This could also be seen by looking at the packet status on the Dynamixel Manager. Even new wires had this issue. In some cases, the power would disconnect for long enough to reset the servo (and all servos on the same port). This was confirmed by testing connections using an oscilloscope.

That being said, setting the serial timeout in dynamixel_io.py in dynamixel_driver to a higher value (0.6) and catching the error and trying again helped in cases were loss of connection was brief (but isn't a full solution).
